### ISSUE TITLE
Remote debugging port already in use

### ISSUE THREAD

**Issue by kyledcline** [deivid-rodriguez/byebug#104]
Running foreman with byebug. Followed instructions in [the guide](https://github.com/deivid-rodriguez/byebug/blob/master/GUIDE.md#debugging-remote-programs), but when starting up foreman, I get a signal exception.

Tried a number of random ports, none seem to work.

```
5:01:07 web.1    | started with pid 68237
15:01:07 clock.1  | started with pid 68238
15:01:07 worker.1 | started with pid 68239
15:01:08 web.1    | I, [2015-01-14T15:01:08.429773 #68237]  INFO -- : Refreshing Gem list
15:01:11 clock.1  | /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/byebug-3.5.1/lib/byebug/remote.rb:52:in `initialize': Address already in use - bind(2) for "localhost" port 9877 (Errno::EADDRINUSE)
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/byebug-3.5.1/lib/byebug/remote.rb:52:in `new'
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/byebug-3.5.1/lib/byebug/remote.rb:52:in `start_control'
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/byebug-3.5.1/lib/byebug/remote.rb:31:in `start_server'
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/config/environments/development.rb:59:in `block in <top (required)>'
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/railtie.rb:210:in `instance_eval'
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/railtie.rb:210:in `configure'
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/railtie.rb:182:in `configure'
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/config/environments/development.rb:1:in `<top (required)>'
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `block in require'
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:232:in `load_dependency'
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/engine.rb:594:in `block (2 levels) in <class:Engine>'
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/engine.rb:593:in `each'
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/engine.rb:593:in `block in <class:Engine>'
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/initializable.rb:30:in `instance_exec'
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/initializable.rb:30:in `run'
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/initializable.rb:55:in `block in run_initializers'
15:01:11 clock.1  | 	from /Users/kylecline/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
15:01:11 clock.1  | 	from /Users/kylecline/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
15:01:11 clock.1  | 	from /Users/kylecline/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:418:in `block (2 levels) in each_strongly_connected_component_from'
15:01:11 clock.1  | 	from /Users/kylecline/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
15:01:11 clock.1  | 	from /Users/kylecline/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:417:in `block in each_strongly_connected_component_from'
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/initializable.rb:44:in `each'
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/initializable.rb:44:in `tsort_each_child'
15:01:11 clock.1  | 	from /Users/kylecline/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:411:in `call'
15:01:11 clock.1  | 	from /Users/kylecline/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:411:in `each_strongly_connected_component_from'
15:01:11 clock.1  | 	from /Users/kylecline/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
15:01:11 clock.1  | 	from /Users/kylecline/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:345:in `each'
15:01:11 clock.1  | 	from /Users/kylecline/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:345:in `call'
15:01:11 clock.1  | 	from /Users/kylecline/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
15:01:11 clock.1  | 	from /Users/kylecline/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
15:01:11 clock.1  | 	from /Users/kylecline/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/initializable.rb:54:in `run_initializers'
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/application.rb:300:in `initialize!'
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/railtie.rb:194:in `public_send'
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/railtie.rb:194:in `method_missing'
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/config/environment.rb:5:in `<top (required)>'
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/lib/clock.rb:3:in `require_relative'
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/lib/clock.rb:3:in `<top (required)>'
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/clockwork-1.1.0/bin/clockwork:12:in `require'
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/clockwork-1.1.0/bin/clockwork:12:in `<top (required)>'
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/bin/clockwork:23:in `load'
15:01:11 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/bin/clockwork:23:in `<main>'
15:01:11 clock.1  | exited with code 1
15:01:11 system   | sending SIGTERM to all processes
15:01:11 worker.1 | rake aborted!
SIGTERM received
15:01:11 worker.1 | SignalException: SIGTERM
15:01:11 worker.1 | /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/initializable.rb:44:in `block in tsort_each_child'
15:01:11 worker.1 | /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/initializable.rb:44:in `select'
15:01:11 worker.1 | /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/initializable.rb:44:in `tsort_each_child'
15:01:11 worker.1 | /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/initializable.rb:54:in `run_initializers'
15:01:11 worker.1 | /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/application.rb:300:in `initialize!'
15:01:11 worker.1 | /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/railtie.rb:194:in `public_send'
15:01:11 worker.1 | /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/railtie.rb:194:in `method_missing'
15:01:11 worker.1 | /Users/kylecline/btcs_wallet/config/environment.rb:5:in `<top (required)>'
15:01:11 worker.1 | /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
15:01:11 worker.1 | /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `block in require'
15:01:11 worker.1 | /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:232:in `load_dependency'
15:01:11 worker.1 | /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
15:01:11 worker.1 | /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/application.rb:276:in `require_environment!'
15:01:11 worker.1 | /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/application.rb:389:in `block in run_tasks_blocks'
15:01:11 worker.1 | Tasks: TOP => jobs:work => jobs:environment_options => environment
15:01:11 worker.1 | (See full trace by running task with --trace)
15:01:11 worker.1 | exited with code 1
15:01:12 web.1    | I, [2015-01-14T15:01:12.906404 #68237]  INFO -- : listening on addr=0.0.0.0:5000 fd=16
15:01:12 web.1    | I, [2015-01-14T15:01:12.973664 #68237]  INFO -- : master process ready
15:01:12 web.1    | I, [2015-01-14T15:01:12.974116 #68237]  INFO -- : reaped #<Process::Status: pid 68242 exit 0> worker=1
15:01:12 web.1    | I, [2015-01-14T15:01:12.974354 #68237]  INFO -- : reaped #<Process::Status: pid 68241 exit 0> worker=0
15:01:13 web.1    | I, [2015-01-14T15:01:13.076964 #68237]  INFO -- : reaped #<Process::Status: pid 68243 exit 0> worker=2
15:01:13 web.1    | I, [2015-01-14T15:01:13.082247 #68237]  INFO -- : master complete
15:01:13 web.1    | exited with code 0
```

**Comment by deivid-rodriguez** [comment]
Could you try specifiying 0 as the port? Also, could you confirm the bug using last master?

**Comment by kyledcline** [comment]
Specifying port `0`:

Foreman starts but does not finish initialization. Browsing localhost:5000 doesn't load anything.

```
13:58:40 web.1    | started with pid 75836
13:58:40 clock.1  | started with pid 75837
13:58:40 worker.1 | started with pid 75838
13:58:41 web.1    | I, [2015-01-15T13:58:41.510195 #75836]  INFO -- : Refreshing Gem list
```

`bundle exec byebug -R localhost:0` outputs

```
Connecting to byebug server localhost:0...
/Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/byebug-3.5.1/lib/byebug/remote.rb:68:in `initialize': Can't assign requested address - connect(2) for "localhost" port 0 (Errno::EADDRNOTAVAIL)
	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/byebug-3.5.1/lib/byebug/remote.rb:68:in `new'
	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/byebug-3.5.1/lib/byebug/remote.rb:68:in `start_client'
	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/byebug-3.5.1/lib/byebug/runner.rb:66:in `run'
	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/byebug-3.5.1/bin/byebug:5:in `<top (required)>'
	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/bin/byebug:23:in `load'
	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/bin/byebug:23:in `<main>'
```

Will try with master and report back.

**Comment by kyledcline** [comment]
Pulled master thru my Gemfile into vendor/cache via:

`gem 'byebug', git: 'https://github.com/deivid-rodriguez/byebug.git', branch: 'master'`
and `bundle update`

`foreman start` crashes:
```
14:04:25 web.1    | started with pid 76334
14:04:25 clock.1  | started with pid 76335
14:04:25 worker.1 | started with pid 76336
14:04:26 web.1    | I, [2015-01-15T14:04:26.823108 #76334]  INFO -- : Refreshing Gem list
14:04:29 clock.1  | /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require': cannot load such file -- byebug/byebug (LoadError)
14:04:29 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `block in require'
14:04:29 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:232:in `load_dependency'
14:04:29 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
14:04:29 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/cache/byebug-99750fa7e668/lib/byebug/core.rb:1:in `<top (required)>'
14:04:29 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
14:04:29 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `block in require'
14:04:29 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:232:in `load_dependency'
14:04:29 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
14:04:29 clock.1  | 	from /Users/kylecline/btcs_wallet/vendor/cache/byebug-99750fa7e668/lib/byebug.rb:1:in `<top (required)>'
14:04:29 clock.1  | 	from /Users/kylecline/.rvm/gems/ruby-2.1.4@global/gems/bundler-1.7.9/lib/bundler/runtime.rb:76:in `require'
14:04:29 clock.1  | 	from /Users/kylecline/.rvm/gems/ruby-2.1.4@global/gems/bundler-1.7.9/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
14:04:29 clock.1  | 	from /Users/kylecline/.rvm/gems/ruby-2.1.4@global/gems/bundler-1.7.9/lib/bundler/runtime.rb:72:in `each'
14:04:29 clock.1  | 	from /Users/kylecline/.rvm/gems/ruby-2.1.4@global/gems/bundler-1.7.9/lib/bundler/runtime.rb:72:in `block in require'
14:04:29 clock.1  | 	from /Users/kylecline/.rvm/gems/ruby-2.1.4@global/gems/bundler-1.7.9/lib/bundler/runtime.rb:61:in `each'
14:04:29 clock.1  | 	from /Users/kylecline/.rvm/gems/ruby-2.1.4@global/gems/bundler-1.7.9/lib/bundler/runtime.rb:61:in `require'
14:04:29 clock.1  | 	from /Users/kylecline/.rvm/gems/ruby-2.1.4@global/gems/bundler-1.7.9/lib/bundler.rb:134:in `require'
```

**Comment by deivid-rodriguez** [comment]
Are you sure it installed properly? That error message seems to point out an installation problem.

**Comment by deivid-rodriguez** [comment]
@kyledcline I've finally reviewed this myself and fixed the issues I found. It should be working fine now against last master.

**Comment by marcinwyszynski** [comment]
This is happening to myself from master, too.

**Comment by deivid-rodriguez** [comment]
@marcinwyszynski Give me a reproducible example and I'll reopen! :)

**Comment by ryanb** [comment]
I ran into this today. It was due to Spring starting the Byebug server in the background. What I ended up doing is using the `remote_byebug` method instead of starting the server ahead of time.
