### ISSUE TITLE
it fails to stop on breakpoints on raven

### ISSUE THREAD

**Issue by x-yuri** [deivid-rodriguez/byebug#111]
Consider the following app:

`Gemfile`:

```ruby
source "https://rubygems.org"
ruby '2.1.5'

gem 'sinatra', git: 'https://github.com/sinatra/sinatra.git', ref: 'b39d72d'
gem 'sentry-raven', '~>0.12.2'
gem 'rspec', '~>3.1.0'
gem 'rack-test', '~>0.6.2'
```

`1.rb`:

```ruby
require 'rubygems'
require 'bundler/setup'

require 'sinatra'
require 'sentry-raven'

Raven.configure(true) do |config|
  config.dsn = '...'
end

use Raven::Rack

get '/' do
  raise 'test exception'
end

ENV['RACK_ENV'] = 'test'

require 'rack/test'

describe 'app' do
  include Rack::Test::Methods

  def app
    @app || Sinatra::Application
  end

  it 'passes errors to Raven' do
byebug
    get '/'
  end
end
```

Additionally, I've added some debug statements:

https://github.com/getsentry/raven-ruby/blob/0.12.3/lib/raven/base.rb#L75:

```ruby
    def send(evt)
puts 'inside Raven.send'
p client.method(:send).source_location
      client.send(evt)
```

https://github.com/getsentry/raven-ruby/blob/0.12.3/lib/raven/client.rb#L25:

```ruby
    def initialize(configuration)
puts 'inside Raven::Client.initialize'
      @configuration = configuration
```

https://github.com/getsentry/raven-ruby/blob/0.12.3/lib/raven/client.rb#L19:

```ruby
    def send(event)
puts 'inside Raven::Client#send'
      unless configuration.send_in_current_environment?
```

Then, when I run the spec:

```
$ rspec 1.rb
inside Raven::Client.initialize

[24, 33] in /home/yuri/_/1/1.rb
   24: 
   25:   def app
   26:     @app || Sinatra::Application
   27:   end
   28: 
   29:   it 'passes errors to Raven' do
   30: byebug
=> 31:     get '/'
   32:   end
   33: end
(byebug) break Raven:Client#send
Created breakpoint 1 at Raven::Client#send
(byebug) c
D, [2015-01-21T13:32:31.726195 #20660] DEBUG -- : ** [Raven] Collecting RuntimeError: test exception
inside Raven.send
["/home/yuri/.gem/ruby/2.1.5/gems/sentry-raven-0.12.3/lib/raven/client.rb", 26]
inside Raven::Client#send
D, [2015-01-21T13:32:31.781984 #20660] DEBUG -- : ** [Raven] Sending event 32353d9aaee7a19247ecef773b3bf66f to Sentry
E, [2015-01-21T13:32:32.415408 #20660] ERROR -- : ** [Raven] Unable to record event with remote Sentry server (Raven::Error - Unknown transport scheme '')
E, [2015-01-21T13:32:32.415720 #20660] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/sentry-raven-0.12.3/lib/raven/client.rb:91:in `transport'
E, [2015-01-21T13:32:32.415873 #20660] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/sentry-raven-0.12.3/lib/raven/client.rb:45:in `send'
E, [2015-01-21T13:32:32.416041 #20660] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/sentry-raven-0.12.3/lib/raven/base.rb:78:in `send'
E, [2015-01-21T13:32:32.416195 #20660] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/sentry-raven-0.12.3/lib/raven/base.rb:116:in `block in capture_exception'
E, [2015-01-21T13:32:32.416346 #20660] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/sentry-raven-0.12.3/lib/raven/base.rb:143:in `send_or_skip'
E, [2015-01-21T13:32:32.416503 #20660] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/sentry-raven-0.12.3/lib/raven/base.rb:110:in `capture_exception'
E, [2015-01-21T13:32:32.416653 #20660] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/sentry-raven-0.12.3/lib/raven/integrations/rack.rb:29:in `capture_exception'
E, [2015-01-21T13:32:32.416832 #20660] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/sentry-raven-0.12.3/lib/raven/integrations/rack.rb:66:in `rescue in call'
E, [2015-01-21T13:32:32.417001 #20660] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/sentry-raven-0.12.3/lib/raven/integrations/rack.rb:60:in `call'
E, [2015-01-21T13:32:32.417176 #20660] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
E, [2015-01-21T13:32:32.417328 #20660] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
E, [2015-01-21T13:32:32.417501 #20660] ERROR -- : ** [Raven] Failed to submit event: RuntimeError: test exception
.

Finished in 25.6 seconds (files took 0.47548 seconds to load)
1 example, 0 failures
```

**Comment by deivid-rodriguez** [comment]
It should be fixed in last master, could you give it a try and let me know?

**Comment by x-yuri** [comment]
With last `master` there's an extra error when setting breakpoint:

```
inside Raven::Client.initialize

[24, 33] in /home/yuri/_/1/1.rb
   24: 
   25:   def app
   26:     @app || Sinatra::Application
   27:   end
   28: 
   29:   it 'passes errors to Raven' do
   30: byebug
=> 31:     get '/'
   32:   end
   33: end
(byebug) break Raven:Client#send
*** NoMethodError Exception: undefined method `Raven' for #<RSpec::ExampleGroups::App:0x007fa4efb90ac8 @__memoized=nil>

Successfully created breakpoint with id 1
(byebug) c
D, [2015-01-22T01:46:14.036140 #12699] DEBUG -- : ** [Raven] Collecting RuntimeError: test exception
inside Raven.send
["/home/yuri/.gem/ruby/2.1.5/gems/sentry-raven-0.12.3/lib/raven/client.rb", 26]
inside Raven::Client#send
D, [2015-01-22T01:46:14.124232 #12699] DEBUG -- : ** [Raven] Sending event 3d79cdc3fa1e545b7f18df6a09b47728 to Sentry
E, [2015-01-22T01:46:15.137503 #12699] ERROR -- : ** [Raven] Unable to record event with remote Sentry server (Raven::Error - Unknown transport scheme '')
E, [2015-01-22T01:46:15.137862 #12699] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/sentry-raven-0.12.3/lib/raven/client.rb:91:in `transport'
E, [2015-01-22T01:46:15.138073 #12699] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/sentry-raven-0.12.3/lib/raven/client.rb:45:in `send'
E, [2015-01-22T01:46:15.138280 #12699] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/sentry-raven-0.12.3/lib/raven/base.rb:78:in `send'
E, [2015-01-22T01:46:15.138482 #12699] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/sentry-raven-0.12.3/lib/raven/base.rb:116:in `block in capture_exception'
E, [2015-01-22T01:46:15.138685 #12699] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/sentry-raven-0.12.3/lib/raven/base.rb:143:in `send_or_skip'
E, [2015-01-22T01:46:15.138886 #12699] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/sentry-raven-0.12.3/lib/raven/base.rb:110:in `capture_exception'
E, [2015-01-22T01:46:15.139100 #12699] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/sentry-raven-0.12.3/lib/raven/integrations/rack.rb:29:in `capture_exception'
E, [2015-01-22T01:46:15.139302 #12699] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/sentry-raven-0.12.3/lib/raven/integrations/rack.rb:66:in `rescue in call'
E, [2015-01-22T01:46:15.139515 #12699] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/sentry-raven-0.12.3/lib/raven/integrations/rack.rb:60:in `call'
E, [2015-01-22T01:46:15.139774 #12699] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
E, [2015-01-22T01:46:15.139976 #12699] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
E, [2015-01-22T01:46:15.140187 #12699] ERROR -- : ** [Raven] Failed to submit event: RuntimeError: test exception
.

Finished in 9.09 seconds (files took 0.49067 seconds to load)
1 example, 0 failures
```

**Comment by deivid-rodriguez** [comment]
Can you try setting it using `break Raven:Client#send`, notice the double `:`

**Comment by x-yuri** [comment]
Oh, so you've fixed this thing with colons `:`... Indeed, with `break Raven::Client#send` it works.

**Comment by deivid-rodriguez** [comment]
Yep, the old syntax was weird and was not actually working. Byebug would think `Raven` was a filename and `Client#send` a line number, because of the `file:line` syntax.

Cheers!
