### ISSUE TITLE
> undefined method `autosave' for nil:NilClass

### ISSUE THREAD

**Issue by MaximeArnstamm** [deivid-rodriguez/byebug#176]
This is a weird one : when i use byebug while running rspec, it fails with this stacktrace.
It fails with each type of rspec tests (controller, model, request).
This seems like a configuration issue, but i can't see where.

```
[7, 16] in .../app/controllers/api/v1/billings_controller.rb
    7:       # TODO list
    8:
    9:       # TODO upload
   10:       def create
   11:         byebug
=> 12:         @user = User.find(params[:user_id])
   13:         authorize @user
   14:
   15:         @event = Event.find(params[:event_id])
   16:         @rsvp = @event.rsvps.where(:user_id == @user.id).first
NoMethodError at /api/v1/users/1/events/1/billings
==================================================

> undefined method `autosave' for nil:NilClass

app/controllers/api/v1/billings_controller.rb, line 12
------------------------------------------------------

''' ruby
    7         # TODO list
    8
    9         # TODO upload
   10         def create
   11           byebug
>  12           @user = User.find(params[:user_id])
   13           authorize @user
   14
   15           @event = Event.find(params[:event_id])
   16           @rsvp = @event.rsvps.where(:user_id == @user.id).first
   17           if !@rsvp
'''

App backtrace
-------------

 - app/controllers/api/v1/billings_controller.rb:12:in `create'
 - spec/utils/request_helpers.rb:7:in `post_json'
 - spec/requests/billings_controller_spec.rb:78:in `block (3 levels) in <top (required)>'

Full backtrace
--------------

 - byebug (5.0.0) lib/byebug/processors/command_processor.rb:99:in `ensure in process_commands'
 - byebug (5.0.0) lib/byebug/processors/command_processor.rb:99:in `process_commands'
 - byebug (5.0.0) lib/byebug/processors/command_processor.rb:48:in `at_line'
 - byebug (5.0.0) lib/byebug/context.rb:90:in `at_line'
 - app/controllers/api/v1/billings_controller.rb:12:in `create'
 - actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
 - actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
 - actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
 - actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
 - activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
 - activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
 - activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
 - activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
 - activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
 - activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
 - actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
 - actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
 - actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
 - activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
 - activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
 - activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
 - actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
 - actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
 - activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
 - actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
 - actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
 - actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
 - actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
 - actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
 - actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
 - actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
 - actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
 - actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
 - actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
 - warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
 - warden (1.2.3) lib/warden/manager.rb:34:in `call'
 - rack (1.6.4) lib/rack/etag.rb:24:in `call'
 - rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
 - rack (1.6.4) lib/rack/head.rb:13:in `call'
 - actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
 - actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
 - rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
 - rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
 - actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
 - activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
 - activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
 - actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
 - activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
 - activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
 - activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
 - actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
 - actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
 - better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
 - better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
 - better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
 - actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
 - actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
 - railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
 - railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
 - activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
 - activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
 - activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
 - railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
 - quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
 - actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
 - rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
 - rack (1.6.4) lib/rack/runtime.rb:18:in `call'
 - activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
 - rack (1.6.4) lib/rack/lock.rb:17:in `call'
 - actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
 - rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
 - railties (4.2.1) lib/rails/engine.rb:518:in `call'
 - railties (4.2.1) lib/rails/application.rb:164:in `call'
 - rack-test (0.6.3) lib/rack/mock_session.rb:30:in `request'
 - rack-test (0.6.3) lib/rack/test.rb:244:in `process_request'
 - rack-test (0.6.3) lib/rack/test.rb:124:in `request'
 - actionpack (4.2.1) lib/action_dispatch/testing/integration.rb:297:in `process'
 - actionpack (4.2.1) lib/action_dispatch/testing/integration.rb:38:in `post'
 - actionpack (4.2.1) lib/action_dispatch/testing/integration.rb:344:in `block (2 levels) in <module:Runner>'
 - spec/utils/request_helpers.rb:7:in `post_json'
 - spec/requests/billings_controller_spec.rb:78:in `block (3 levels) in <top (required)>'
 - rspec-core (3.3.2) lib/rspec/core/example.rb:206:in `block in run'
 - rspec-core (3.3.2) lib/rspec/core/example.rb:430:in `block in with_around_and_singleton_context_hooks'
 - rspec-core (3.3.2) lib/rspec/core/example.rb:388:in `block in with_around_example_hooks'
 - rspec-core (3.3.2) lib/rspec/core/hooks.rb:478:in `block in run'
 - rspec-core (3.3.2) lib/rspec/core/hooks.rb:618:in `block in run_around_example_hooks_for'
 - rspec-core (3.3.2) lib/rspec/core/example.rb:273:in `call'
 - rspec-rails (3.3.3) lib/rspec/rails/adapters.rb:127:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
 - rspec-core (3.3.2) lib/rspec/core/example.rb:378:in `instance_exec'
 - rspec-core (3.3.2) lib/rspec/core/hooks.rb:389:in `execute_with'
 - rspec-core (3.3.2) lib/rspec/core/hooks.rb:620:in `block (2 levels) in run_around_example_hooks_for'
 - rspec-core (3.3.2) lib/rspec/core/example.rb:273:in `call'
 - rspec-core (3.3.2) lib/rspec/core/hooks.rb:621:in `run_around_example_hooks_for'
 - rspec-core (3.3.2) lib/rspec/core/hooks.rb:478:in `run'
 - rspec-core (3.3.2) lib/rspec/core/example.rb:388:in `with_around_example_hooks'
 - rspec-core (3.3.2) lib/rspec/core/example.rb:430:in `with_around_and_singleton_context_hooks'
 - rspec-core (3.3.2) lib/rspec/core/example.rb:203:in `run'
 - rspec-core (3.3.2) lib/rspec/core/example_group.rb:559:in `block in run_examples'
 - rspec-core (3.3.2) lib/rspec/core/example_group.rb:555:in `run_examples'
 - rspec-core (3.3.2) lib/rspec/core/example_group.rb:521:in `run'
 - rspec-core (3.3.2) lib/rspec/core/example_group.rb:522:in `block in run'
 - rspec-core (3.3.2) lib/rspec/core/example_group.rb:522:in `run'
 - rspec-core (3.3.2) lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs'
 - rspec-core (3.3.2) lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs'
 - rspec-core (3.3.2) lib/rspec/core/configuration.rb:1627:in `with_suite_hooks'
 - rspec-core (3.3.2) lib/rspec/core/runner.rb:114:in `block in run_specs'
 - rspec-core (3.3.2) lib/rspec/core/reporter.rb:77:in `report'
 - rspec-core (3.3.2) lib/rspec/core/runner.rb:113:in `run_specs'
 - rspec-core (3.3.2) lib/rspec/core/runner.rb:89:in `run'
 - rspec-core (3.3.2) lib/rspec/core/runner.rb:73:in `run'
 - rspec-core (3.3.2) lib/rspec/core/runner.rb:41:in `invoke'
 - rspec-core (3.3.2) exe/rspec:4:in `<top (required)>'
 - /usr/local/var/rbenv/versions/2.2.2/bin/rspec:23:in `<main>'
```
Here's my Gemfile.lock
```
GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.2.1)
      actionpack (= 4.2.1)
      actionview (= 4.2.1)
      activejob (= 4.2.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.1)
      actionview (= 4.2.1)
      activesupport (= 4.2.1)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.1)
    actionview (4.2.1)
      activesupport (= 4.2.1)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.1)
    activejob (4.2.1)
      activesupport (= 4.2.1)
      globalid (>= 0.3.0)
    activemodel (4.2.1)
      activesupport (= 4.2.1)
      builder (~> 3.1)
    activerecord (4.2.1)
      activemodel (= 4.2.1)
      activesupport (= 4.2.1)
      arel (~> 6.0)
    activesupport (4.2.1)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.3.8)
    airborne (0.1.20)
      activesupport (>= 3.0.0)
      rack-test (~> 0.6, >= 0.6.2)
      rest-client (~> 1.7, >= 1.7.3)
      rspec (~> 3.1, >= 3.1.0)
    annotate (2.6.10)
      activerecord (>= 3.2, <= 4.3)
      rake (~> 10.4)
    arel (6.0.3)
    autoprefixer-rails (6.0.3)
      execjs
      json
    bcrypt (3.1.10)
    better_errors (2.1.1)
      coderay (>= 1.0.0)
      erubis (>= 2.6.6)
      rack (>= 0.9.0)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    bootstrap-sass (3.3.5.1)
      autoprefixer-rails (>= 5.0.0.1)
      sass (>= 3.3.0)
    builder (3.2.2)
    byebug (5.0.0)
      columnize (= 0.9.0)
    coderay (1.1.0)
    coffee-rails (4.1.0)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1.1)
    columnize (0.9.0)
    countries (1.1.0)
      currencies (~> 0.4.2)
      i18n_data (~> 0.7.0)
    country_select (2.4.0)
      countries (~> 1.1.0)
      sort_alphabetical (~> 1.0)
    currencies (0.4.2)
    database_cleaner (1.5.0)
    debug_inspector (0.0.2)
    delayed_job (4.1.1)
      activesupport (>= 3.0, < 5.0)
    delayed_job_active_record (4.1.0)
      activerecord (>= 3.0, < 5)
      delayed_job (>= 3.0, < 5)
    devise (3.5.2)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    diff-lcs (1.2.5)
    domain_name (0.5.24)
      unf (>= 0.0.5, < 1.0.0)
    erubis (2.7.0)
    execjs (2.6.0)
    font-awesome-sass (4.4.0)
      sass (>= 3.2)
    globalid (0.3.6)
      activesupport (>= 4.1.0)
    http-cookie (1.0.2)
      domain_name (~> 0.5)
    i18n (0.7.0)
    i18n_data (0.7.0)
    jbuilder (2.3.2)
      activesupport (>= 3.0.0, < 5)
      multi_json (~> 1.2)
    jquery-rails (4.0.5)
      rails-dom-testing (~> 1.0)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    json (1.8.3)
    kaminari (0.16.3)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    launchy (2.4.3)
      addressable (~> 2.3)
    letter_opener (1.4.1)
      launchy (~> 2.2)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    method_source (0.8.2)
    mime-types (2.6.2)
    mini_portile (0.6.2)
    minitest (5.8.1)
    multi_json (1.11.2)
    netrc (0.10.3)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    orm_adapter (0.5.0)
    pg (0.18.3)
    pry (0.10.2)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    pry-byebug (3.2.0)
      byebug (~> 5.0)
      pry (~> 0.10)
    pry-rails (0.3.4)
      pry (>= 0.9.10)
    puma (2.14.0)
    pundit (1.0.1)
      activesupport (>= 3.0.0)
    quiet_assets (1.1.0)
      railties (>= 3.1, < 5.0)
    rack (1.6.4)
    rack-test (0.6.3)
      rack (>= 1.0)
    rack-timeout (0.3.2)
    rails (4.2.1)
      actionmailer (= 4.2.1)
      actionpack (= 4.2.1)
      actionview (= 4.2.1)
      activejob (= 4.2.1)
      activemodel (= 4.2.1)
      activerecord (= 4.2.1)
      activesupport (= 4.2.1)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.1)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.7)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.2)
      loofah (~> 2.0)
    rails-push-notifications (0.2.2)
      rails (>= 3.2)
      ruby-push-notifications (~> 0.3)
    rails_12factor (0.0.3)
      rails_serve_static_assets
      rails_stdout_logging
    rails_serve_static_assets (0.0.4)
    rails_stdout_logging (0.0.4)
    railties (4.2.1)
      actionpack (= 4.2.1)
      activesupport (= 4.2.1)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (10.4.2)
    rdoc (4.2.0)
    responders (2.1.0)
      railties (>= 4.2.0, < 5)
    rest-client (1.8.0)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 3.0)
      netrc (~> 0.7)
    rspec (3.3.0)
      rspec-core (~> 3.3.0)
      rspec-expectations (~> 3.3.0)
      rspec-mocks (~> 3.3.0)
    rspec-core (3.3.2)
      rspec-support (~> 3.3.0)
    rspec-expectations (3.3.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.3.0)
    rspec-mocks (3.3.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.3.0)
    rspec-rails (3.3.3)
      actionpack (>= 3.0, < 4.3)
      activesupport (>= 3.0, < 4.3)
      railties (>= 3.0, < 4.3)
      rspec-core (~> 3.3.0)
      rspec-expectations (~> 3.3.0)
      rspec-mocks (~> 3.3.0)
      rspec-support (~> 3.3.0)
    rspec-support (3.3.0)
    ruby-push-notifications (0.3.1)
      builder (~> 3.0)
    sass (3.4.18)
    sass-rails (5.0.4)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    sdoc (0.4.1)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    simple_form (3.2.0)
      actionpack (~> 4.0)
      activemodel (~> 4.0)
    simple_token_authentication (1.10.0)
      actionmailer (>= 3.2.6, < 5)
      actionpack (>= 3.2.6, < 5)
      devise (~> 3.2)
    slop (3.6.0)
    sort_alphabetical (1.0.2)
      unicode_utils (>= 1.2.2)
    spring (1.4.0)
    sprockets (3.3.5)
      rack (> 1, < 3)
    sprockets-rails (2.3.3)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    sqlite3 (1.3.10)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (2.0.1)
    turbolinks (2.5.3)
      coffee-rails
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.2)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.1)
    unicode_utils (1.4.0)
    warden (1.2.3)
      rack (>= 1.0)

PLATFORMS
  ruby

DEPENDENCIES
  airborne
  annotate
  better_errors
  binding_of_caller
  bootstrap-sass
  byebug
  coffee-rails (~> 4.1.0)
  country_select
  database_cleaner
  delayed_job_active_record
  devise
  font-awesome-sass
  jbuilder (~> 2.0)
  jquery-rails
  kaminari
  letter_opener
  pg
  pry-byebug
  pry-rails
  puma
  pundit
  quiet_assets
  rack-timeout
  rails (= 4.2.1)
  rails-push-notifications (~> 0.2.0)
  rails_12factor
  rspec-core
  rspec-rails
  sass-rails (~> 5.0)
  sdoc (~> 0.4.0)
  simple_form
  simple_token_authentication (~> 1.0)
  spring
  sqlite3
  turbolinks
  uglifier (>= 1.3.0)

BUNDLED WITH
   1.10.3
```

**Comment by deivid-rodriguez** [comment]
Can you try to reproduce this against latest `byebug`?

**Comment by MaximeArnstamm** [comment]
Ok, that's my fault. Pry-byebug forced byebug to stay at 5.0.0. Once updated, it works.

Thanks

**Comment by deivid-rodriguez** [comment]
:+1:

**Comment by danielminsalesforce** [comment]
Im using the 11.0.1 version but I'm still getting that error

**Comment by deivid-rodriguez** [comment]
Can you open a new ticket with repro steps? Thanks!
