### ISSUE TITLE
`backtrace` doesn't work inside `url_for` actionview's method

### ISSUE THREAD

**Issue by jcoyne** [deivid-rodriguez/byebug#199]
Using byebug 8.2.1 and ruby 2.2.4
```
[74, 83] in /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionview-4.2.5/lib/action_view/routing_url_for.rb
   74:     #
   75:     #   <%= url_for(action: 'index', controller: '/users') %>
   76:     #   # Specify absolute path with beginning slash
   77:     #   # => /users
   78:     def url_for(options = nil)
=> 79:       case options
   80:       when String
   81:         options
   82:       when nil
   83:         super(only_path: _generate_paths_by_default)
(byebug) bt
*** undefined method `parameters' for #<String:0x007ff914c442e8>
(byebug) backtrace
*** undefined method `parameters' for #<String:0x007ff914c442e8>
(byebug) method(:backtrace)
*** NameError Exception: undefined method `backtrace' for class `#<Class:0x007ff913a72f10>'
```

**Comment by deivid-rodriguez** [comment]
@jcoyne I hope to have a look at this soon. Could you check if it's reproducible in `rails 5.0.0.rc1` + `ruby 2.3.1`?

**Comment by jcoyne** [comment]
I'm trying to test this and now i'm getting:

```
     Errno::ENOENT:
       No such file or directory @ rb_sysopen - /Users/jcoyne/.byebugrc
     # /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/byebug-9.0.3/lib/byebug/interfaces/script_interface.rb:8:in `initialize'
     # /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/byebug-9.0.3/lib/byebug/interfaces/script_interface.rb:8:in `open'
     # /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/byebug-9.0.3/lib/byebug/interfaces/script_interface.rb:8:in `initialize'
     # /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/byebug-9.0.3/lib/byebug/core.rb:91:in `new'
     # /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/byebug-9.0.3/lib/byebug/core.rb:91:in `run_rc_file'
     # /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/byebug-9.0.3/lib/byebug/core.rb:50:in `run_init_script'
     # /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/byebug-9.0.3/lib/byebug/attacher.rb:16:in `attach'
     # /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/byebug-9.0.3/lib/byebug/attacher.rb:30:in `byebug'
```

**Comment by deivid-rodriguez** [comment]
@jcoyne This is very strange... the line previous to the one that's failing is checking for the existence of that file... https://github.com/deivid-rodriguez/byebug/blob/master/lib/byebug/core.rb#L88-L91 :astonished:

**Comment by jcoyne** [comment]
My fault. I was mocking `File#exist?`

**Comment by deivid-rodriguez** [comment]
Good! So? Any luck?

**Comment by deivid-rodriguez** [comment]
Just tried this myself and it's now working fine, so I'm going to close.
