### ISSUE TITLE
Can't load pry-byebug

### ISSUE THREAD

**Issue by frojasg** [deivid-rodriguez/byebug#214]
When I try to load pry-byebug i get the following error

```ruby
bundle exec irb
irb(main):001:0> require 'pry-byebug'
NameError: undefined method `get_pr_arguments' for module `Byebug::FrameFunctions'
	from /Users/frojas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/debugger-xml-0.4.1/lib/byebug/commands/frame.rb:12:in `alias_method'
	from /Users/frojas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/debugger-xml-0.4.1/lib/byebug/commands/frame.rb:12:in `<module:FrameFunctions>'
	from /Users/frojas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/debugger-xml-0.4.1/lib/byebug/commands/frame.rb:2:in `<module:Byebug>'
	from /Users/frojas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/debugger-xml-0.4.1/lib/byebug/commands/frame.rb:1:in `<top (required)>'
	from /Users/frojas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/byebug-8.2.2/lib/byebug/commands.rb:13:in `require'
	from /Users/frojas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/byebug-8.2.2/lib/byebug/commands.rb:13:in `<top (required)>'
	from /Users/frojas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/byebug-8.2.2/lib/byebug/core.rb:8:in `require'
	from /Users/frojas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/byebug-8.2.2/lib/byebug/core.rb:8:in `<top (required)>'
	from /Users/frojas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pry-byebug-3.3.0/lib/byebug/processors/pry_processor.rb:1:in `require'
	from /Users/frojas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pry-byebug-3.3.0/lib/byebug/processors/pry_processor.rb:1:in `<top (required)>'
	from /Users/frojas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pry-byebug-3.3.0/lib/pry-byebug/pry_ext.rb:1:in `require'
	from /Users/frojas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pry-byebug-3.3.0/lib/pry-byebug/pry_ext.rb:1:in `<top (required)>'
	from /Users/frojas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pry-byebug-3.3.0/lib/pry-byebug/cli.rb:2:in `require'
	from /Users/frojas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pry-byebug-3.3.0/lib/pry-byebug/cli.rb:2:in `<top (required)>'
	from /Users/frojas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pry-0.10.3/lib/pry/plugins.rb:38:in `require'
	from /Users/frojas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pry-0.10.3/lib/pry/plugins.rb:38:in `load_cli_options'
	from /Users/frojas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pry-0.10.3/lib/pry/cli.rb:40:in `block in add_plugin_options'
	from /Users/frojas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pry-0.10.3/lib/pry/cli.rb:39:in `each'
	from /Users/frojas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pry-0.10.3/lib/pry/cli.rb:39:in `add_plugin_options'
	from /Users/frojas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pry-0.10.3/lib/pry/cli.rb:107:in `<top (required)>'
	from /Users/frojas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pry-0.10.3/lib/pry.rb:150:in `require'
	from /Users/frojas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pry-0.10.3/lib/pry.rb:150:in `<top (required)>'
	from /Users/frojas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pry-byebug-3.3.0/lib/pry-byebug.rb:1:in `require'
	from /Users/frojas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pry-byebug-3.3.0/lib/pry-byebug.rb:1:in `<top (required)>'
	from (irb):1:in `require'
	from (irb):1
	from /Users/frojas/.rbenv/versions/2.3.0/bin/irb:11:in `<main>'irb(main):002:0>
```

I'm using ruby 2.3.0, byebug (8.2.2) and pry-byebug (3.3.0). Everything look good on pry-byebug (3.2.0)

**Comment by deivid-rodriguez** [comment]
Does it get fixed if you remove the `debugger-xml` gem?

**Comment by frojasg** [comment]
yes, it does! Thanks!

**Comment by deivid-rodriguez** [comment]
You are welcome! :wink:
