### ISSUE TITLE
invalid index (IndexError) on FreeBSD when stepping into function

### ISSUE THREAD

**Issue by robertgrimm** [deivid-rodriguez/byebug#241]
I'm getting "invalid index" errors when stepping into functions on FreeBSD.

My trivial test program:
```ruby
def foo
  "foo"
end

require "byebug"
debugger
foo
```

On a clean FreeBSD 10.3 install with just Ruby 2.1.8p440 (the version that ships with FreeBSD) and byebug 8.2.4 installed, I get the following results:

```
[1, 7] in /usr/home/robg/debugger_test.rb
   1: def foo
   2:   "foo"
   3: end
   4: 
   5: require "byebug"
   6: debugger
=> 7: foo
(byebug) s

[1, 7] in /usr/home/robg/debugger_test.rb
   1: def foo
=> 2:   "foo"
   3: end
   4: 
   5: require "byebug"
   6: debugger
   7: foo
/usr/local/lib/ruby/gems/2.1/gems/byebug-8.2.4/lib/byebug/history.rb:118:in `[]': invalid index (IndexError)
	from /usr/local/lib/ruby/gems/2.1/gems/byebug-8.2.4/lib/byebug/history.rb:118:in `ignore?'
	from /usr/local/lib/ruby/gems/2.1/gems/byebug-8.2.4/lib/byebug/history.rb:57:in `push'
	from /usr/local/lib/ruby/gems/2.1/gems/byebug-8.2.4/lib/byebug/history.rb:30:in `block in restore'
	from /usr/local/lib/ruby/gems/2.1/gems/byebug-8.2.4/lib/byebug/history.rb:30:in `reverse_each'
	from /usr/local/lib/ruby/gems/2.1/gems/byebug-8.2.4/lib/byebug/history.rb:30:in `restore'
	from /usr/local/lib/ruby/gems/2.1/gems/byebug-8.2.4/lib/byebug/interface.rb:114:in `autorestore'
	from /usr/local/lib/ruby/gems/2.1/gems/byebug-8.2.4/lib/byebug/processors/command_processor.rb:132:in `before_repl'
	from /usr/local/lib/ruby/gems/2.1/gems/byebug-8.2.4/lib/byebug/processors/command_processor.rb:96:in `process_commands'
	from /usr/local/lib/ruby/gems/2.1/gems/byebug-8.2.4/lib/byebug/processors/command_processor.rb:56:in `at_line'
	from /usr/local/lib/ruby/gems/2.1/gems/byebug-8.2.4/lib/byebug/context.rb:96:in `at_line'
	from ./debugger_test.rb:2:in `foo'
	from ./debugger_test.rb:7:in `<main>'
```

This only appears to happen when stepping into (s) the function.  Continuing (c) and stepping over (n) the function both appear to work.

The only other platform I tried this on was OSX and everything appears to work fine.

**Comment by robertgrimm** [comment]
I did some more testing and this happens when compiling Ruby against libedit instead of readline and FreeBSD defaults to compiling against libedit.  For my purposes, compiling against readline was enough to work around this issue, however, there may be folks who would really prefer to compile against libedit.

**Comment by deivid-rodriguez** [comment]
@robertgrimm Thanks for reporting this, it's interesting and seems easy to reproduce thanks to your investigation. Will let you know if I give it a try!
