### ISSUE TITLE
Byebug crashes when debugging a function named `to_int`

### ISSUE THREAD

**Issue by iblue** [deivid-rodriguez/byebug#278]
byebug crashes when you are debugging inside a function that is called `to_int` which expects one or more parameters. Tested with `byebug 9.0.5` on `ruby 2.2.3p173`.
# Code

``` ruby
# Save as demo.rb
require "byebug"

def to_int(param)
  byebug
  42
end

to_int(23)
```
# Usage

Run code and try to continue.

```
iblue@raven:~/byebugbug$ ruby demo.rb 

[1, 8] in /home/iblue/byebugbug/demo.rb
   1: require "byebug"
   2: 
   3: def to_int(param)
   4:   byebug
=> 5:   42
   6: end
   7: 
   8: to_int(23)
(byebug) c
demo.rb:3:in `to_int': wrong number of arguments (0 for 1) (ArgumentError)
        from /home/iblue/.rvm/gems/ruby-2.2.3/gems/byebug-9.0.5/lib/byebug/history.rb:39:in `initialize'
        from /home/iblue/.rvm/gems/ruby-2.2.3/gems/byebug-9.0.5/lib/byebug/history.rb:39:in `open'
        from /home/iblue/.rvm/gems/ruby-2.2.3/gems/byebug-9.0.5/lib/byebug/history.rb:39:in `save'
        from /home/iblue/.rvm/gems/ruby-2.2.3/gems/byebug-9.0.5/lib/byebug/interface.rb:110:in `autosave'
        from /home/iblue/.rvm/gems/ruby-2.2.3/gems/byebug-9.0.5/lib/byebug/processors/command_processor.rb:121:in `after_repl'
        from /home/iblue/.rvm/gems/ruby-2.2.3/gems/byebug-9.0.5/lib/byebug/processors/command_processor.rb:100:in `process_commands'
        from /home/iblue/.rvm/gems/ruby-2.2.3/gems/byebug-9.0.5/lib/byebug/processors/command_processor.rb:56:in `at_line'
        from /home/iblue/.rvm/gems/ruby-2.2.3/gems/byebug-9.0.5/lib/byebug/context.rb:96:in `at_line'
        from demo.rb:5:in `to_int'
        from demo.rb:8:in `<main>'
```

**Comment by deivid-rodriguez** [comment]
Hi @iblue, this seems like a bug in Ruby, not in Byebug.

Doing something weird enough like:

```
def to_int(param)
  IO.new('a', 'w')
  42
end

to_int(23)
```
reproduces it too without the need for `byebug`.
