### ISSUE TITLE
IRB completion seems broken

### ISSUE THREAD

**Issue by benjaminbauer** [deivid-rodriguez/byebug#62]
byebug 2.7.0
rails 3.2.17
irb 0.9.6
ruby 2.1.1

When I'm in a debugging session in one of my rails (3.2.17) initializers and hit <kbd>Tab</kbd>, I get the following exception.
```
lINTERNAL ERROR!!! undefined method `workspace' for nil:NilClass
	/home/benni/.rbenv/versions/2.1.1/lib/ruby/2.1.0/irb/completion.rb:39:in `block in <module:InputCompletor>'
	/home/benni/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/byebug-2.7.0/lib/byebug/interfaces/local_interface.rb:70:in `call'
	/home/benni/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/byebug-2.7.0/lib/byebug/interfaces/local_interface.rb:70:in `readline'
	/home/benni/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/byebug-2.7.0/lib/byebug/interfaces/local_interface.rb:70:in `readline'
	/home/benni/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/byebug-2.7.0/lib/byebug/interfaces/local_interface.rb:25:in `read_command'
	/home/benni/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/byebug-2.7.0/lib/byebug/command_processor.rb:175:in `process_commands'
	/home/benni/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/byebug-2.7.0/lib/byebug/command_processor.rb:93:in `at_line'
	/home/benni/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/byebug-2.7.0/lib/byebug/command_processor.rb:53:in `block in at_line'
	/home/benni/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/byebug-2.7.0/lib/byebug/command_processor.rb:51:in `synchronize'
	/home/benni/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/byebug-2.7.0/lib/byebug/command_processor.rb:51:in `at_line'
	/home/benni/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/byebug-2.7.0/lib/byebug/context.rb:82:in `at_line'
```

**Comment by hh** [comment]
Google brought me to this issue while trying to get tab completion working in byebug.
Maybe I'm going about it the wrong way.

```
[hh@mba rvm]$ ls
Gemfile  Gemfile.lock  runme_then_hit_tab.rb
[hh@mba rvm]$ cat Gemfile
source 'https://rubygems.org'
gem 'byebug'
[hh@mba rvm]$ cat runme_then_hit_tab.rb 
require 'byebug'
byebug
puts 'a'
[hh@mba rvm]$ bundle exec ruby runme_then_hit_tab.rb 

[1, 3] in /home/hh/rvm/runme_then_hit_tab.rb
   1: require 'byebug'
   2: byebug
=> 3: puts 'a'
(byebug) require 'irb/completion'
true
(byebug) [HIT TAB HERE]/home/hh/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/irb/completion.rb:38:in `block in <module:InputCompletor>': undefined method `workspace' for nil:NilClass (NoMethodError)
	from /home/hh/.rvm/gems/ruby-2.2.0/gems/byebug-6.0.2/lib/byebug/interfaces/local_interface.rb:21:in `call'
	from /home/hh/.rvm/gems/ruby-2.2.0/gems/byebug-6.0.2/lib/byebug/interfaces/local_interface.rb:21:in `readline'
	from /home/hh/.rvm/gems/ruby-2.2.0/gems/byebug-6.0.2/lib/byebug/interfaces/local_interface.rb:21:in `readline'
	from /home/hh/.rvm/gems/ruby-2.2.0/gems/byebug-6.0.2/lib/byebug/interface.rb:68:in `prepare_input'
	from /home/hh/.rvm/gems/ruby-2.2.0/gems/byebug-6.0.2/lib/byebug/interface.rb:52:in `read_input'
	from /home/hh/.rvm/gems/ruby-2.2.0/gems/byebug-6.0.2/lib/byebug/interface.rb:35:in `read_command'
	from /home/hh/.rvm/gems/ruby-2.2.0/gems/byebug-6.0.2/lib/byebug/processors/command_processor.rb:139:in `repl'
	from /home/hh/.rvm/gems/ruby-2.2.0/gems/byebug-6.0.2/lib/byebug/processors/command_processor.rb:95:in `process_commands'
	from /home/hh/.rvm/gems/ruby-2.2.0/gems/byebug-6.0.2/lib/byebug/processors/command_processor.rb:75:in `at_line'
	from /home/hh/.rvm/gems/ruby-2.2.0/gems/byebug-6.0.2/lib/byebug/context.rb:109:in `at_line'
	from runme_then_hit_tab.rb:3:in `<main>'
[hh@mba rvm]$ cat Gemfile.lock 
GEM
  remote: https://rubygems.org/
  specs:
    byebug (6.0.2)

PLATFORMS
  ruby

DEPENDENCIES
  byebug

BUNDLED WITH
   1.10.2
[hh@mba rvm]$ cat .ruby-version 
ruby-2.2.0
```

**Comment by deivid-rodriguez** [comment]
Hi. I think this is not `byebug`'s fault. To use `irb`'s completion you need to be inside `irb`! Type `irb` from `byebug`'s prompt and then `require 'irb/completion'`.

Hopefully at some point `byebug` will provide its own completions.

Closing...
